flir-functions.inc: temporarily disabled flir_rev_update() function
suddenly (?), "bitbake flir-image" stopped working due to
flir_rev_update() update of rootfs image
Until sorted out, the flir_rev_update() is replaced with a
dummy function body
(original body still present in flir_rev_updatex() )

Cut from bitbake error message:
ERROR: flir-image-1.0-r0 do_image: Error executing a python function in exec_python_func()
...
...REPRODUCIBLE_TIMESTAMP_ROOTFS...
...
Exception: bb.process.ExecutionError: Execution of '/media/rouge/uffe/cirrus33/build_evco/tmp/work/evco-oe-linux-gnueabi/flir-image/1.0-r0/temp/run.flir_rev_update.3466798' failed with exit code 128
...